# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f28b1814a034250e872b69ad9b8864ec2ca06b9df6f4ec70f8db261cfc4970fe2af0bc54f7411c498983afc20fd1dc3179d939236ada5e3eaf13b5dd4bbe07f

test:
  secret_key_base: 215f400fcb49268b90fec596409348cae415eac534464ecde2ae786734fcadebd9bb9060e1a796827d442cc12c4d9f05cfd3b1a526dce3de4579bfef8e3ba0d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
